#!/bin/bash


usage() {
    if test -z "$*"; then
        RC=0
    else
        echo "Error:  $*" >&2
        RC=1
    fi
    cat >&2 <<EOF
Usage: $0 [-t TAG] IMAGE
      -t TAG:   Tag final image with TAG
      IMAGE:    Docker image tag to build on
EOF
    exit $RC
}

BASE_IMAGE=$1; shift
IMAGE_TAG=${BASE_IMAGE}_overlay
while getopts :t: ARG; do
    case $ARG in
    t) IMAGE_TAG=$OPTARG ;;
    # Usage
    h) usage ;;
    :) usage "Option -$OPTARG requires an argument" ;;
    *) usage "Illegal option -$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))


BUILD_ARGS=(
    --build-arg BASE_IMAGE=$BASE_IMAGE
    --tag $IMAGE_TAG
    )

docker build "${BUILD_ARGS[@]}" - <<EOF
ARG BASE_IMAGE
FROM ${BASE_IMAGE}

RUN apt-get update \
    && apt-get install -y python-pip \
    && pip install catkin-tools

RUN echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/50-nopass \
    && chmod 600 /etc/sudoers.d/50-nopass

RUN apt-get update \
    && apt-get install -y ccache

EOF
