#!/bin/bash -e


usage() {
    if test -z "$*"; then
        RC=0
    else
        echo "Error:  $*" >&2
        RC=1
    fi
    cat >&2 <<-EOF
	Build ROS Docker overlay image
	Usage: $0 [args...]
	    -b ROCKER_BASE_IMAGE:  Base image to start from
	    -t ROCKER_IMAGE_TAG:   Final image tag
	    -w:                    Install package deps from workspace sources
	                           (ROCKER_WORKSPACE_DEPS=true)
	    If a '.rocker' file exists in the workspace, it will be sourced
	      and any \$ROCKER_* will be read
	EOF
    exit $RC
}

dockerfile_base() {
    cat <<-EOF
	ARG ROCKER_BASE_IMAGE
	FROM \${ROCKER_BASE_IMAGE}

	RUN apt-get update \
	    && apt-get install -y python3-pip \
	    && apt-get clean \
	    && pip3 install catkin-tools

	RUN echo "%sudo ALL=(ALL:ALL) NOPASSWD: ALL" >> /etc/sudoers.d/50-nopass \
	    && chmod 600 /etc/sudoers.d/50-nopass

	RUN apt-get update \
	    && apt-get install -y \
	        ccache \
	        clang \
	        clang-tidy \
	        clang-tools \
	        gdb \
	        xterm \
	        wget \
	    && apt-get clean

	EOF
}

dockerfile_workspace() {
    cat <<-EOF
	COPY . /tmp/ros_ws
	RUN cd /tmp/ros_ws \
	    && rosdep install -y --rosdistro \$ROS_DISTRO --ignore-src --from-paths src

	EOF
}

# Read from any .rocker config
if test -f $(pwd)/.rocker; then
    source $(pwd)/.rocker
fi

# Command-line args override those settings
while getopts :t:b:wh ARG; do
    case $ARG in
	# Build args
	t) ROCKER_IMAGE_TAG=$OPTARG ;;
	b) ROCKER_BASE_IMAGE=$OPTARG ;;
	w) ROCKER_WORKSPACE_DEPS=true ;;
	# Usage
	h) usage ;;
	:) usage "Option -$OPTARG requires an argument" ;;
	*) usage "Illegal option -$OPTARG" ;;
    esac
done
shift $(($OPTIND - 1))

# Check options and set defaults
test -n "$ROCKER_BASE_IMAGE" || usage "No base image specified"
ROCKER_IMAGE_TAG=${ROCKER_IMAGE_TAG:-${ROCKER_BASE_IMAGE}_overlay}
if test "$ROCKER_WORKSPACE_DEPS" != true; then
    ROCKER_WORKSPACE_DEPS=false
fi

# Construct `docker build` args
BUILD_ARGS=(
    --build-arg ROCKER_BASE_IMAGE=$ROCKER_BASE_IMAGE
    --tag $ROCKER_IMAGE_TAG
    )
if $ROCKER_WORKSPACE_DEPS; then
    BUILD_ARGS+=(
	-f -
	$(pwd)
    )
else
    BUILD_ARGS+=( - )
fi

# Run `docker build`, feeding the Dockerfile over stdin
{
    dockerfile_base
    if $ROCKER_WORKSPACE_DEPS; then
	dockerfile_workspace
    fi
} | {
    set -x
    exec docker build "${BUILD_ARGS[@]}"
}
